-- Real translations for every MessageCode the server can return, so LanguageManager.get(MessageCode)
-- resolves to player-facing text instead of the "!CODE!" fallback (review §3.3). The ERROR group_type
-- matches CHAR_NAME_TAKEN's existing precedent (V2). CHAR_NAME_TAKEN itself is already seeded there;
-- this covers every other current MessageCode value (SUCCESS and ERROR_UNKNOWN included).
INSERT INTO localization_keys (key_name, group_type) VALUES
    ('SUCCESS', 'ERROR'), ('ERROR_UNKNOWN', 'ERROR'), ('CHAR_CREATE_SUCCESS', 'ERROR'),
    ('CHAR_MAX_SLOTS_REACHED', 'ERROR'), ('LOGIN_FAILED_INVALID_TOKEN', 'ERROR'),
    ('STAT_POINTS_INSUFFICIENT', 'ERROR'), ('STAT_CAP_EXCEEDED', 'ERROR'),
    ('SKILL_NODE_NOT_FOUND', 'ERROR'), ('SKILL_LEVEL_GATE_NOT_MET', 'ERROR'),
    ('SKILL_FACTION_MISMATCH', 'ERROR'), ('SKILL_RANK_MAXED', 'ERROR'),
    ('SKILL_POINTS_INSUFFICIENT', 'ERROR'), ('SKILL_GOLD_INSUFFICIENT', 'ERROR'),
    ('LOADOUT_ITEM_NOT_OWNED', 'ERROR'), ('LOADOUT_SKILL_SLOTS_EXCEEDED', 'ERROR'),
    ('LOADOUT_WEIGHT_EXCEEDED', 'ERROR'), ('SHOP_ITEM_NOT_FOUND', 'ERROR'),
    ('SHOP_NOTHING_TO_REPAIR', 'ERROR'), ('SHOP_GOLD_INSUFFICIENT', 'ERROR'),
    ('SHOP_TOKEN_INSUFFICIENT', 'ERROR'), ('QUEST_NOT_FOUND', 'ERROR'),
    ('QUEST_NOT_COMPLETE', 'ERROR'), ('QUEST_ALREADY_CLAIMED', 'ERROR'),
    ('QUEST_DAILY_CLAIM_CAP_REACHED', 'ERROR'), ('QUEST_INVALID_REWARD_CHOICE', 'ERROR'),
    ('DAILY_BATTLE_CAP_REACHED', 'ERROR'), ('RANKED_LEVEL_GATE_NOT_MET', 'ERROR'),
    ('LADDER_NOT_RANKED_ELIGIBLE', 'ERROR'), ('LADDER_NO_REWARD_THIS_RANK', 'ERROR'),
    ('LADDER_ALREADY_CLAIMED', 'ERROR'), ('TITLE_NOT_UNLOCKED', 'ERROR'),
    ('CHAR_INVALID_APPEARANCE', 'ERROR');

INSERT INTO localization_values (key_id, lang_code, text_value) VALUES
    ((SELECT id FROM localization_keys WHERE key_name = 'SUCCESS'), 'en_US', 'Success.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SUCCESS'), 'tr_TR', 'Başarılı.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'ERROR_UNKNOWN'), 'en_US', 'An unexpected error occurred. Please try again.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'ERROR_UNKNOWN'), 'tr_TR', 'Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'CHAR_CREATE_SUCCESS'), 'en_US', 'Character created successfully.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'CHAR_CREATE_SUCCESS'), 'tr_TR', 'Karakter başarıyla oluşturuldu.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'CHAR_MAX_SLOTS_REACHED'), 'en_US', 'You have reached your maximum number of character slots.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'CHAR_MAX_SLOTS_REACHED'), 'tr_TR', 'Maksimum karakter slot sayısına ulaştınız.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LOGIN_FAILED_INVALID_TOKEN'), 'en_US', 'Login failed: invalid identity token.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LOGIN_FAILED_INVALID_TOKEN'), 'tr_TR', 'Giriş başarısız: geçersiz kimlik belirteci.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'STAT_POINTS_INSUFFICIENT'), 'en_US', 'You don''t have enough stat points for that.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'STAT_POINTS_INSUFFICIENT'), 'tr_TR', 'Bunun için yeterli stat puanınız yok.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'STAT_CAP_EXCEEDED'), 'en_US', 'That would exceed the maximum value for this stat.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'STAT_CAP_EXCEEDED'), 'tr_TR', 'Bu, bu stat için izin verilen maksimum değeri aşar.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_NODE_NOT_FOUND'), 'en_US', 'That skill node could not be found.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_NODE_NOT_FOUND'), 'tr_TR', 'Bu yetenek düğümü bulunamadı.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_LEVEL_GATE_NOT_MET'), 'en_US', 'Your character level is too low to learn this skill.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_LEVEL_GATE_NOT_MET'), 'tr_TR', 'Bu yeteneği öğrenmek için karakter seviyeniz yetersiz.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_FACTION_MISMATCH'), 'en_US', 'This skill isn''t available to your faction.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_FACTION_MISMATCH'), 'tr_TR', 'Bu yetenek fraksiyonunuz için mevcut değil.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_RANK_MAXED'), 'en_US', 'This skill is already at its maximum rank.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_RANK_MAXED'), 'tr_TR', 'Bu yetenek zaten maksimum seviyede.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_POINTS_INSUFFICIENT'), 'en_US', 'You don''t have enough skill points for that.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_POINTS_INSUFFICIENT'), 'tr_TR', 'Bunun için yeterli yetenek puanınız yok.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_GOLD_INSUFFICIENT'), 'en_US', 'You don''t have enough gold for that.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SKILL_GOLD_INSUFFICIENT'), 'tr_TR', 'Bunun için yeterli altınınız yok.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LOADOUT_ITEM_NOT_OWNED'), 'en_US', 'You don''t own one of the items in that loadout.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LOADOUT_ITEM_NOT_OWNED'), 'tr_TR', 'Bu düzenlemedeki eşyalardan birine sahip değilsiniz.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LOADOUT_SKILL_SLOTS_EXCEEDED'), 'en_US', 'That loadout has too many skills equipped.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LOADOUT_SKILL_SLOTS_EXCEEDED'), 'tr_TR', 'Bu düzenleme çok fazla yetenek içeriyor.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LOADOUT_WEIGHT_EXCEEDED'), 'en_US', 'Those weapons are too heavy to carry together.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LOADOUT_WEIGHT_EXCEEDED'), 'tr_TR', 'Bu silahlar birlikte taşınamayacak kadar ağır.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SHOP_ITEM_NOT_FOUND'), 'en_US', 'That item is not available in the shop.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SHOP_ITEM_NOT_FOUND'), 'tr_TR', 'Bu eşya mağazada mevcut değil.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SHOP_NOTHING_TO_REPAIR'), 'en_US', 'There is nothing that needs repairing.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SHOP_NOTHING_TO_REPAIR'), 'tr_TR', 'Onarılması gereken bir şey yok.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SHOP_GOLD_INSUFFICIENT'), 'en_US', 'You don''t have enough gold for that purchase.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SHOP_GOLD_INSUFFICIENT'), 'tr_TR', 'Bu satın alma için yeterli altınınız yok.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SHOP_TOKEN_INSUFFICIENT'), 'en_US', 'You don''t have enough tokens for that.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'SHOP_TOKEN_INSUFFICIENT'), 'tr_TR', 'Bunun için yeterli jetonunuz yok.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'QUEST_NOT_FOUND'), 'en_US', 'That quest could not be found.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'QUEST_NOT_FOUND'), 'tr_TR', 'Bu görev bulunamadı.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'QUEST_NOT_COMPLETE'), 'en_US', 'You haven''t completed this quest yet.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'QUEST_NOT_COMPLETE'), 'tr_TR', 'Bu görevi henüz tamamlamadınız.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'QUEST_ALREADY_CLAIMED'), 'en_US', 'You''ve already claimed this quest''s reward.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'QUEST_ALREADY_CLAIMED'), 'tr_TR', 'Bu görevin ödülünü zaten aldınız.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'QUEST_DAILY_CLAIM_CAP_REACHED'), 'en_US', 'You''ve reached today''s quest reward limit.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'QUEST_DAILY_CLAIM_CAP_REACHED'), 'tr_TR', 'Bugünkü görev ödülü limitine ulaştınız.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'QUEST_INVALID_REWARD_CHOICE'), 'en_US', 'That is not a valid reward choice for this quest.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'QUEST_INVALID_REWARD_CHOICE'), 'tr_TR', 'Bu, bu görev için geçerli bir ödül seçeneği değil.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'DAILY_BATTLE_CAP_REACHED'), 'en_US', 'You''ve reached today''s battle limit.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'DAILY_BATTLE_CAP_REACHED'), 'tr_TR', 'Bugünkü savaş limitine ulaştınız.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'RANKED_LEVEL_GATE_NOT_MET'), 'en_US', 'Your character level is too low for ranked battles.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'RANKED_LEVEL_GATE_NOT_MET'), 'tr_TR', 'Karakter seviyeniz derecelendirmeli savaşlar için yetersiz.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LADDER_NOT_RANKED_ELIGIBLE'), 'en_US', 'This character isn''t eligible for the ranked ladder yet.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LADDER_NOT_RANKED_ELIGIBLE'), 'tr_TR', 'Bu karakter henüz sıralama ligine uygun değil.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LADDER_NO_REWARD_THIS_RANK'), 'en_US', 'There''s no reward for this rank.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LADDER_NO_REWARD_THIS_RANK'), 'tr_TR', 'Bu sıralama için ödül bulunmuyor.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LADDER_ALREADY_CLAIMED'), 'en_US', 'You''ve already claimed this month''s ladder reward.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'LADDER_ALREADY_CLAIMED'), 'tr_TR', 'Bu ayın lig ödülünü zaten aldınız.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'TITLE_NOT_UNLOCKED'), 'en_US', 'You haven''t unlocked that title yet.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'TITLE_NOT_UNLOCKED'), 'tr_TR', 'Bu unvanın kilidini henüz açmadınız.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'CHAR_INVALID_APPEARANCE'), 'en_US', 'That appearance combination isn''t available.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'CHAR_INVALID_APPEARANCE'), 'tr_TR', 'Bu görünüm kombinasyonu mevcut değil.');
