-- CharacterCreationScreen wizard redesign (M4 screen pass, prompt 39). This screen was the least
-- localized in the app: every label, option, stat name, stat tooltip and dialog was a hardcoded English
-- literal, with not a single key of its own seeded. Same content-seed shape as V23/V25/V27 — no schema
-- change, plain UI keys outside MessageCodeLocalizationCoverageTest's reach, so they land in the same
-- change as their get(...) call sites. UI_BTN_BACK is already seeded (V2) and is not repeated here.
-- The two faction taglines follow the real faction names agreed in 03-lore-and-worldbuilding.md
-- (The Wardens / The Skyborn). %d fills via String.format at the call site.
INSERT INTO localization_keys (key_name, group_type) VALUES
    ('UI_LBL_CREATE_CHARACTER', 'UI'), ('UI_LBL_STEP_IDENTITY', 'UI'), ('UI_LBL_STEP_APPEARANCE', 'UI'),
    ('UI_LBL_STEP_STATS', 'UI'), ('UI_LBL_CHARACTER_NAME', 'UI'), ('UI_HINT_ENTER_NAME', 'UI'),
    ('UI_LBL_FACTION', 'UI'), ('UI_FACTION_WARDENS_NAME', 'UI'), ('UI_FACTION_WARDENS_TAGLINE', 'UI'),
    ('UI_FACTION_SKYBORN_NAME', 'UI'), ('UI_FACTION_SKYBORN_TAGLINE', 'UI'),
    ('UI_LBL_GENDER', 'UI'), ('UI_OPT_GENDER_MALE', 'UI'), ('UI_OPT_GENDER_FEMALE', 'UI'),
    ('UI_LBL_HAIR_TYPE', 'UI'), ('UI_OPT_HAIR_SHORT', 'UI'), ('UI_OPT_HAIR_LONG', 'UI'), ('UI_OPT_HAIR_BALD', 'UI'),
    ('UI_LBL_HAIR_COLOR', 'UI'), ('UI_OPT_HAIRCOLOR_BLACK', 'UI'), ('UI_OPT_HAIRCOLOR_BROWN', 'UI'),
    ('UI_OPT_HAIRCOLOR_BLONDE', 'UI'), ('UI_OPT_HAIRCOLOR_RED', 'UI'),
    ('UI_LBL_SKIN_COLOR', 'UI'), ('UI_OPT_SKINCOLOR_PALE', 'UI'), ('UI_OPT_SKINCOLOR_LIGHT', 'UI'),
    ('UI_OPT_SKINCOLOR_TAN', 'UI'), ('UI_OPT_SKINCOLOR_DARK', 'UI'),
    ('UI_MSG_CHARACTER_PREVIEW_PLACEHOLDER', 'UI'), ('UI_LBL_POINTS_REMAINING', 'UI'),
    ('UI_STAT_STRENGTH', 'UI'), ('UI_STAT_DESC_STRENGTH', 'UI'),
    ('UI_STAT_DEXTERITY', 'UI'), ('UI_STAT_DESC_DEXTERITY', 'UI'),
    ('UI_STAT_VITALITY', 'UI'), ('UI_STAT_DESC_VITALITY', 'UI'),
    ('UI_STAT_INTELLIGENCE', 'UI'), ('UI_STAT_DESC_INTELLIGENCE', 'UI'),
    ('UI_STAT_WISDOM', 'UI'), ('UI_STAT_DESC_WISDOM', 'UI'),
    ('UI_STAT_SPIRIT', 'UI'), ('UI_STAT_DESC_SPIRIT', 'UI'),
    ('UI_STAT_SPEED', 'UI'), ('UI_STAT_DESC_SPEED', 'UI'),
    ('UI_STAT_INSIGHT', 'UI'), ('UI_STAT_DESC_INSIGHT', 'UI'),
    ('UI_BTN_NEXT', 'UI'), ('UI_BTN_CREATE', 'UI'),
    ('UI_LBL_INVALID_NAME_TITLE', 'UI'), ('UI_MSG_INVALID_NAME', 'UI'), ('UI_BTN_OK', 'UI');

INSERT INTO localization_values (key_id, lang_code, text_value) VALUES
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_CREATE_CHARACTER'), 'tr_TR', 'Karakter Oluştur'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_CREATE_CHARACTER'), 'en_US', 'Create character'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_STEP_IDENTITY'), 'tr_TR', 'Kimlik'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_STEP_IDENTITY'), 'en_US', 'Identity'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_STEP_APPEARANCE'), 'tr_TR', 'Görünüm'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_STEP_APPEARANCE'), 'en_US', 'Appearance'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_STEP_STATS'), 'tr_TR', 'Özellikler'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_STEP_STATS'), 'en_US', 'Stats'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_CHARACTER_NAME'), 'tr_TR', 'Karakter adı'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_CHARACTER_NAME'), 'en_US', 'Character name'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_HINT_ENTER_NAME'), 'tr_TR', 'İsim girin'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_HINT_ENTER_NAME'), 'en_US', 'Enter name'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_FACTION'), 'tr_TR', 'Fraksiyon'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_FACTION'), 'en_US', 'Faction'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_FACTION_WARDENS_NAME'), 'tr_TR', 'Muhafızlar'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_FACTION_WARDENS_NAME'), 'en_US', 'The Wardens'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_FACTION_WARDENS_TAGLINE'), 'tr_TR', 'Teslimiyetle gelen kesinlik. Maskeyi tak, nişanını bırak — asla ıskalamazsın.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_FACTION_WARDENS_TAGLINE'), 'en_US', 'Certainty through submission. Wear the mask, surrender your aim — you will never miss.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_FACTION_SKYBORN_NAME'), 'tr_TR', 'Gökdoğanlar'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_FACTION_SKYBORN_NAME'), 'en_US', 'The Skyborn'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_FACTION_SKYBORN_TAGLINE'), 'tr_TR', 'Riskle gelen özgürlük. Yarı sis, yarı yıldırım — ıskalayabilirsin ama köşeye sıkıştırılamazsın.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_FACTION_SKYBORN_TAGLINE'), 'en_US', 'Freedom through risk. Half mist, half lightning — you might miss, but you can''t be pinned down.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_GENDER'), 'tr_TR', 'Cinsiyet'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_GENDER'), 'en_US', 'Gender'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_GENDER_MALE'), 'tr_TR', 'Erkek'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_GENDER_MALE'), 'en_US', 'Male'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_GENDER_FEMALE'), 'tr_TR', 'Kadın'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_GENDER_FEMALE'), 'en_US', 'Female'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_HAIR_TYPE'), 'tr_TR', 'Saç tipi'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_HAIR_TYPE'), 'en_US', 'Hair type'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIR_SHORT'), 'tr_TR', 'Kısa'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIR_SHORT'), 'en_US', 'Short'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIR_LONG'), 'tr_TR', 'Uzun'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIR_LONG'), 'en_US', 'Long'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIR_BALD'), 'tr_TR', 'Kel'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIR_BALD'), 'en_US', 'Bald'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_HAIR_COLOR'), 'tr_TR', 'Saç rengi'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_HAIR_COLOR'), 'en_US', 'Hair color'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIRCOLOR_BLACK'), 'tr_TR', 'Siyah'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIRCOLOR_BLACK'), 'en_US', 'Black'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIRCOLOR_BROWN'), 'tr_TR', 'Kahverengi'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIRCOLOR_BROWN'), 'en_US', 'Brown'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIRCOLOR_BLONDE'), 'tr_TR', 'Sarışın'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIRCOLOR_BLONDE'), 'en_US', 'Blonde'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIRCOLOR_RED'), 'tr_TR', 'Kızıl'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_HAIRCOLOR_RED'), 'en_US', 'Red'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_SKIN_COLOR'), 'tr_TR', 'Ten rengi'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_SKIN_COLOR'), 'en_US', 'Skin color'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_SKINCOLOR_PALE'), 'tr_TR', 'Soluk'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_SKINCOLOR_PALE'), 'en_US', 'Pale'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_SKINCOLOR_LIGHT'), 'tr_TR', 'Açık'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_SKINCOLOR_LIGHT'), 'en_US', 'Light'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_SKINCOLOR_TAN'), 'tr_TR', 'Bronz'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_SKINCOLOR_TAN'), 'en_US', 'Tan'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_SKINCOLOR_DARK'), 'tr_TR', 'Koyu'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_OPT_SKINCOLOR_DARK'), 'en_US', 'Dark'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_MSG_CHARACTER_PREVIEW_PLACEHOLDER'), 'tr_TR', 'Karakter önizlemesi yakında'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_MSG_CHARACTER_PREVIEW_PLACEHOLDER'), 'en_US', 'Character preview coming soon'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_POINTS_REMAINING'), 'tr_TR', '%d puan kaldı'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_POINTS_REMAINING'), 'en_US', '%d points remaining'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_STRENGTH'), 'tr_TR', 'Güç'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_STRENGTH'), 'en_US', 'Strength'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_STRENGTH'), 'tr_TR', 'Fiziksel hasarı ve taşıma kapasitesini artırır.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_STRENGTH'), 'en_US', 'Increases physical damage and carry weight.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DEXTERITY'), 'tr_TR', 'Çeviklik'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DEXTERITY'), 'en_US', 'Dexterity'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_DEXTERITY'), 'tr_TR', 'Saldırı hızını ve isabet oranını artırır.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_DEXTERITY'), 'en_US', 'Improves attack speed and accuracy.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_VITALITY'), 'tr_TR', 'Dayanıklılık'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_VITALITY'), 'en_US', 'Vitality'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_VITALITY'), 'tr_TR', 'Maksimum canı ve dirençleri artırır.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_VITALITY'), 'en_US', 'Boosts maximum health and resistances.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_INTELLIGENCE'), 'tr_TR', 'Zeka'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_INTELLIGENCE'), 'en_US', 'Intelligence'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_INTELLIGENCE'), 'tr_TR', 'Büyü hasarını ve etkinliğini artırır.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_INTELLIGENCE'), 'en_US', 'Increases magical damage and effectiveness.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_WISDOM'), 'tr_TR', 'Bilgelik'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_WISDOM'), 'en_US', 'Wisdom'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_WISDOM'), 'tr_TR', 'Büyü hızını ve başarı oranını artırır.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_WISDOM'), 'en_US', 'Improves spell casting speed and success rate.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_SPIRIT'), 'tr_TR', 'Ruh'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_SPIRIT'), 'en_US', 'Spirit'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_SPIRIT'), 'tr_TR', 'Maksimum manayı ve büyü direncini artırır.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_SPIRIT'), 'en_US', 'Boosts maximum mana and magic resistance.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_SPEED'), 'tr_TR', 'Hız'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_SPEED'), 'en_US', 'Speed'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_SPEED'), 'tr_TR', 'Kaçınma şansını ve sıra önceliğini artırır.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_SPEED'), 'en_US', 'Increases dodge chance and turn priority.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_INSIGHT'), 'tr_TR', 'Sezgi'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_INSIGHT'), 'en_US', 'Insight'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_INSIGHT'), 'tr_TR', 'Evcil hayvan etkinliğini ve özel yetenekleri artırır.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_STAT_DESC_INSIGHT'), 'en_US', 'Improves pet effectiveness and special abilities.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_BTN_NEXT'), 'tr_TR', 'İleri'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_BTN_NEXT'), 'en_US', 'Next'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_BTN_CREATE'), 'tr_TR', 'Oluştur'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_BTN_CREATE'), 'en_US', 'Create'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_INVALID_NAME_TITLE'), 'tr_TR', 'Geçersiz İsim'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_LBL_INVALID_NAME_TITLE'), 'en_US', 'Invalid name'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_MSG_INVALID_NAME'), 'tr_TR', 'Lütfen geçerli bir karakter adı girin.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_MSG_INVALID_NAME'), 'en_US', 'Please enter a valid character name.'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_BTN_OK'), 'tr_TR', 'Tamam'),
    ((SELECT id FROM localization_keys WHERE key_name = 'UI_BTN_OK'), 'en_US', 'OK');
